% Add basic paths
startupbasepath = fileparts(mfilename('fullpath')); %C:\... \MATLAB\
startupfolders = {...
    'Phi29_Alex' ...
    'Phi29_Alex/helperFunctions' ...
    'Phi29_Alex/Calibration' ...
    'Testing/GUIDesign' ...
    'Testing/GUIDesign/StepFind_KV' ...
    'Testing/GUIDesign/StepFind_HMM' ...
    'Testing/GUIDesign/Velocity' ...
    'Testing/GUIDesign/Helpers' ...
    'Testing/GUIDesign/ForceExt' ...
    'Testing/GUIDesign/Plotting'};
cellfun(@(x)addpath([startupbasepath filesep x]), startupfolders);
clear startupbasepath startupfolders

format shortG
format compact