function out = viewdata(dat, off, cal, inPath, inOpts)
%Quick viewer. View data by passing a data-offset-cal ## triplet
% On first run, will pop DataOptsPopup to set type
%Can be used simply as commands: basically two of them:
%viewdata 33 12 11 %Process data # 33 with offset # 12 and cal # 11
%viewdata setup %Run manual setup again for options and path

basepath = fullfile('C:', 'Data');
persistent opts path

%Manual setup, run with >>viewdata setup
if strcmpi(dat, 'setup')
    opts = DataOptsPopup;
    path = uigetdir(basepath,'Select data folder (e.g. Data\YYMMDD\');
    %Either get mmddyy from folder name or from *.dat name?
    [~, mmddyy] = fileparts(path);
    mmddyy = mmddyy(1:6);
    opts.mmddyy = mmddyy;
    return
end

%If inOpts is passed, update
if nargin >= 5
    opts = handleOpts(opts, inOpts);
end

%if inPath passed, update
if nargin >=4 && ~isempty(inPath)
    path = inPath;
end

%Default opts: Get from DataOptsPopup
if isempty(opts)
    opts = DataOptsPopup;
    if isempty(opts)
        return
    end
end

%Format path from today's date. Use DataOptsPopup Instrument to do year format
if isempty(path)
    if strncmp(opts.Instrument, 'HiRes', 5)
        datefmt = 'MMDDYY';
    else
        datefmt = 'YYMMDD';
    end
    path = fullfile(basepath, datestr(now, datefmt) );
    [~, mmddyy] = fileparts(path);
    mmddyy = mmddyy(1:6);
    opts.mmddyy = mmddyy;
end

%Try the current path, else pull filepicker
if ~exist(path, 'dir')
    path = uigetdir('Select data folder (e.g. Data\YYMMDD\');
    [~, mmddyy] = fileparts(path);
    mmddyy = mmddyy(1:6);
    opts.mmddyy = mmddyy;
end

%If run as a command, str2double the dat/off/cals
if ischar(dat)
    dat = str2double(dat);
end
if ischar(off)
    off = str2double(off);
end
if ischar(cal)
    cal = str2double(cal);
end

%Add missing stuff that AProcessData would add
opts.comment = 'Generated by @viewdata';

%Process. Will create the processed data file
out = ProcessOneDataV2(path, [dat off cal], opts);
outpath = out.name; %Filename is stored in out.name

%Launch data viewer, either PhageGUI or ForExtGUI based on opts.Protocol
if strcmp(opts.Protocol, 'Force-Extension')
    ForExtGUI_V2(outpath);
else
    PhageGUIv4(outpath);
end
