function pGUI_msgblurb(msgid)
%Shows a message box with info for PhageGUI

if nargin < 1
    msgid = -1;
end

switch msgid
    otherwise
        str = { ...
            'Summary of Figure:' ...
            'PhageGUI has a top row of buttons, a left row of buttons/inputs, and the main plot windows.' ...
            'The buttons are summarized below, and the big graph shows contour(or extension) vs time, bottom shows force vs time, right shows a residence time histogram.' ...
            '' ...
            'Summary of Top Buttons:' ...
            'Loading files: This should work with most .mat files, just load them.' ...
            'Cropping: Set a crop (t1, t2) by selecting two points (left-to-right order), it will show up as red lines. Select a crop right-to-left to delete it.' ...
            'CropID: You can have crops with separate IDs for organization by changing the text to the right of the Crop button.' ...
            'CropID button: Click this to se a summary of the CropIDs of the traces in this folder.' ...
            'Measure: Click two points and it will draw a line and label it with its x-length, y-length, and slope.' ...
            'Trim: Click a region to delete from the trace. Deleted sections are stored in the ''cut'' field, and show up grey.' ...
            'ToWorkspace: Writes the current trace to the workspace with variable names starting with ''gui''.' ...
            'LocNoise: Shows the local noise of the trace, plotted by default anyway.' ...
            'EasyAnalyze: Prompts the user to analyze the cropped data in this folder with a variety of easy-to-use analysis options. See the bottom for more.' ...
            'Aspect Ratio: Alters the aspect ratio of the data to a predefined one, and draws lines with [spacing, offset] set by the numbers below.' ...
            'Custom02: In development, does ... something. Click it and the name shall change to what it does' ...
            'ScaleFCs: For semipassive, shows how the ScaleFeedbackCycle algorithm will straighten the data.' ...
            'Comment: The comment written with the data file (if it exists) is shown here.' ...
            'Print: Saves an image of the PhageGUI window to the current directory, named PhagePrtSc*.png' ...
            'Help: Displays this help window.' ...
            '' ...
            'Summary of Left Buttons:'...
            'Slider: This lets you cycle through the files in the current folder' ...
            'Clear Graph: Clears the main graph of the extra stuff (lines, text, etc. drawn over it), leaving just the data.' ...
            'Filtering options: The trace in the main window will be grey (unfiltered) and colored (filtered, according to the below options:)' ...
            'Filter factor: The half-width of the filter, i.e. 2n+1 points are averaged together. Use [] to filter the same as the decimation amount' ...
            'Decimation factor: How many points to skip, i.e. if DecFact=10 then the filtered trace has 1/10th the points of the original' ...
            'YMin/Max: Shows the default Y-limits for the main graph. The program will use a tighter limit to squeeze tight to the data.' ...
            'PlotCal/Off/Raw/Meta: Shows the Calibration/Offset/Raw Voltages/Metadata for the file, if it has it' ...
            'KDF radio buttons: Shows how the kernel density (= residence time histogram) is plotted on the right, respects crops, options below:' ...
            ' KDF Quick is a simple histogram, KDF Full is a gaussian kernel with SD [the box to the right]. K-V does K-V filtering.' ...
            '' ...
            'Summary of EasyAnalyze:'...
            'EasyAnalyze can do: plot, velocity distribution, and stepfinding.' ...
            'A good place to start to see some basic analysis of your data.' ...
            'I would suggest ' ...
            'See the Filtering Options above for details on how filter/decimation factor work.' ...
            };
        tit = 'Readme for PhageGUI';
end



msgbox(str, tit);