function StepFinding_ATPgS_TagBeforePortion(KernelX,KernelY,LocalMaxInd)
    % Interact with the plot, select the Peak1, Peak2 and Offset then save
    % the results, or simply ignore the trace and move on
    % Create the buttons and handle the GUI elements
    %
    % Gheorghe Chistol, 15 July 2011
    
    % Initialize the buttons and the Peak1, Peak2, Offset variables

    clear global Peak1 Peak2 Offset Status X Y MaxInd; 
    global Peak1 Peak2 Offset Status X Y MaxInd;
    X = KernelX;
    Y = KernelY;
    MaxInd = LocalMaxInd;
    Peak1.Ind          = [];
    Peak1.Handle       = [];
    Peak2.Ind          = [];
    Peak2.Handle       = [];
    Offset.Ind         = MaxInd(1);
    Offset.OriginalInd = MaxInd(1);
    Offset.Handle      = plot(X(Offset.Ind)*[1 1],Y(Offset.Ind)*[0 1],'w','LineWidth',3);
    Status             = 'Ignore'; %ignore status by default
    
    % Create the buttons
    button1 = uicontrol('Style', 'PushButton', 'Units','Normalized',...
                        'Position',[0.0912 0.9124 0.13 0.06],...
                        'String','Correct Offset','FontSize',8,...
                        'CallBack','StepFinding_ATPgS_BeforeGUI(''CorrectOffset'')');

    button2 = uicontrol('Style', 'PushButton','Units','normalized',...
                        'Position',[0.0912+0.14 0.9124 0.13 0.06],...
                        'String','Mark Peak1','FontSize',8,'CallBack',...
                        'StepFinding_ATPgS_BeforeGUI(''MarkPeak1'')');
                    
    button3 = uicontrol('Style', 'PushButton','Units','normalized',...
                        'Position',[0.0912+0.14*2 0.9124 0.13 0.06],...
                        'String','Mark Peak2','FontSize',8,'CallBack',...
                        'StepFinding_ATPgS_BeforeGUI(''MarkPeak2'')');
                    
    button4 = uicontrol('Style', 'PushButton','Units','normalized',...
                        'Position',[0.0912+0.14*3 0.9124 0.13 0.06],...
                        'String','Clear','FontSize',8,'CallBack',...
                        'StepFinding_ATPgS_BeforeGUI(''Clear'')');
                    
%     button5 = uicontrol('Style', 'PushButton','Units','normalized',...
%                         'Position',[0.0912+0.14*4 0.9124 0.13 0.06],...
%                         'String','Save Trace','FontSize',8,'CallBack',...
%                         'StepFinding_ATPgS_BeforeGUI(''SaveTrace'')');
%                     
%     button6 = uicontrol('Style', 'PushButton','Units','normalized',...
%                         'Position',[0.0912+0.14*5 0.9124 0.13 0.06],...
%                         'String','Ignore','FontSize',8,'CallBack',...
%                         'StepFinding_ATPgS_BeforeGUI(''Ignore'')');
end