function Dwell = LLP__SummarizeResults()
% There is a small change: dwell d ends where dwell d+1 starts
% This function summarizes the results generated by LLP__FindLLP() ina
% convenient form. Note that the results are in the following form
% FinalDwells{Phage}{FeedbackCycle}{Section}
% Athough Section is by default just 1, there might be circumstances where
% we would have more than 1 section there. FinalDwells has the following
% fields:
%             Start: [1x23 double]
%            Finish: [1x23 double]
%         StartTime: [1x23 double]
%        FinishTime: [1x23 double]
%         DwellTime: [1x23 double]
%     DwellLocation: [1x23 single]
%        DwellForce: [1x23 single]
%          StepSize: [1x23 single] %step size after a given dwell, step sizes are negative for a step forward and positive for a backtrack
%      StepLocation: [1x23 single]
%         StepForce: [1x23 single]
%         PhageFile: [1x84 char]
%     FeedbackCycle: 3
%         Bandwidth: 100
% 
% USE: Dwell = LLP__SummarizeResults()
%
% Gheorghe Chistol, 03 Dec 2012

    global analysisPath;
    [ResultsFile ResultsFilePath] = uigetfile([ [analysisPath filesep] '*.mat'], 'Please select the Step-Finding Results File','MultiSelect','on');

    if ~iscell(ResultsFile)
        temp = ResultsFile; clear ResultsFile; ResultsFile{1} = temp; clear temp;
    end
    
    Dwell.Duration       = [];
    Dwell.Location       = [];
    Dwell.SizeStepBefore = [];
    Dwell.SizeStepAfter  = [];   
    for FileInd = 1:length(ResultsFile)
        clear FinalDwells;
        load([ResultsFilePath filesep ResultsFile{FileInd}]);
        %FinalDwellsValidated{PhageIndex}{FeedbackCycleIndex}{SegmentIndex}
        for p = 1:length(FinalDwells) %p indexes the Phage
            for fc = 1:length(FinalDwells{p}) %fc indexes the feedback cycle
                for s = 1:length(FinalDwells{p}{fc})
                    CurrDwells = FinalDwells{p}{fc}{s};
                    Dwell.Duration       = [Dwell.Duration        CurrDwells.DwellTime];
                    Dwell.Location       = [Dwell.Location        CurrDwells.DwellLocation];
                    Dwell.SizeStepAfter  = [Dwell.SizeStepAfter  -CurrDwells.StepSize]; %by default, StepSize is referring to the step after a certain dwell
                    Dwell.SizeStepBefore = [Dwell.SizeStepBefore  NaN -CurrDwells.StepSize(1:end-1)]; %the stepsize before the first dwell in a feedback cycle is unknown, therefore the NaN
                end
            end
        end
    end
end